name: CI
on:
  workflow_dispatch:

jobs:
  Test:
    name: Run tests
    strategy:
      matrix:
        os: [macos-latest]
        profile: [PostgreSQL-11]
        jdk: [8]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_buildx: false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run tests
        run: mvn -q clean verify -B -DskipDefault -Dtest=PreparedStatementTest,UnixDomainSocketTest -P ${{ matrix.profile }}
